version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip3 install -r requirements.txt
  build:
    commands:
      - python3 -m pytest --junitxml=pytest_reports/pytest_report.xml

reports:
  pytest_reports:
    files:
      - pytest_report.xml
    base-directory: pytest_reports/
    file-format: JUNITXML
