version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - python3 --version
      - python3 -m venv venv
      - . venv/bin/activate
      - pip3 install -r requirements.txt
      - wget --no-verbose https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/${ALLURE_VERSION}/allure-commandline-${ALLURE_VERSION}.zip
      - unzip -qq allure-commandline-${ALLURE_VERSION}.zip
      - export PATH=$PATH:$PWD/allure-${ALLURE_VERSION}/bin
      - wget --no-verbose https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - sudo dpkg -i google-chrome-stable_current_*.deb
      - sudo apt-get install -f

      # - set -ex \
      #   && wget --no-verbose -O /tmp/chrome.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb \
      #   && (dpkg -i /tmp/chrome.deb || apt-get -fy install) \
      #   && rm /tmp/chrome.deb \
      #   && sed -i 's|HERE/chrome"|HERE/chrome" --disable-setuid-sandbox --no-sandbox|g' "/opt/google/chrome/google-chrome" \
      #   && google-chrome --version
      
  
  build:
    commands:
      - python3 -m pytest --browser=${BROWSER} --env=${ENVIRONMENT} --junitxml=pytest_reports/pytest_report.xml --alluredir=allure-results --html=reports/html_report.html -n auto
  
  post_build:
    commands:
      - allure generate allure-results -o allure-report --clean
      
reports:
  pytest_reports:
    files:
      - pytest_report.xml
    base-directory: pytest_reports/
    file-format: JUNITXML

artifacts:
  files:
    - pytest_reports/pytest_report.xml
    - allure-report/**/*
    - reports/html_report.html
