version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - sudo apt install allure
      - python3 --version
      - python3 -m venv venv
      - . venv/bin/activate
      - pip3 install -r requirements.txt
  
  build:
    commands:
      - python3 -m pytest --browser=chrome-headless --env=qa --junitxml=pytest_reports/pytest_report.xml --alluredir=allure-results -n auto
  
  post_build:
    commands:
      - allure generate --clean allure-results -o allure-report

reports:
  pytest_reports:
    files:
      - pytest_report.xml
    base-directory: pytest_reports/
    file-format: JUNITXML

artifacts:
  files:
    - pytest_reports/pytest_report.xml
    - allure-report/
