version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - python3 --version
      - python3 -m venv venv
      - . venv/bin/activate
      - pip3 install -r requirements.txt
      - printenv
      - pwd
      - wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.27.0/allure-commandline-2.27.0.zip
      - unzip allure-commandline-2.27.0.zip
      - export PATH=$PATH:/allure-2.27.0/bin
      - printenv
  
  build:
    commands:
      - python3 -m pytest --browser=chrome-headless --env=qa --junitxml=pytest_reports/pytest_report.xml --alluredir=allure-results -n auto
  
  post_build:
    commands:
      - allure generate allure-results -o allure-report --clean
      - aws s3 sync allure-report/ s3://myown-testreports/allure-report/

reports:
  pytest_reports:
    files:
      - pytest_report.xml
    base-directory: pytest_reports/
    file-format: JUNITXML

artifacts:
  files:
    - pytest_reports/pytest_report.xml
    - allure-report/**/*
