version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - npm install -g allure-commandline --save-dev
      - python3 --version
      - python3 -m venv venv
      - . venv/bin/activate
      - python3 -m pip3 install --upgrade pip
      - pip3 install -r requirements.txt
  
  build:
    commands:
      - python3 -m pytest --browser=chrome-headless --env=qa --html=reports/report.html -n auto

reports:
  html_reports:
    files:
      - report.html
    base-directory: reports/
    file-format: HTML
