version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - npm install -g allure-commandline --save-dev
      - python3 --version
      - python3 -m venv venv
      - . venv/bin/activate
      - pip3 install -r requirements.txt
  
  build:
    commands:
      - python3 -m pytest --browser=chrome-headless --env=qa --alluredir=allure-results -n auto
      
  post_build:
    commands:
      - allure generate allure-results -o allure-report --clean

reports:
  pytest_reports:
    files: 
      - **/*
    base-directory: allure-report/
    file-format: HTML
